# Generated by Django 3.1.7 on 2021-04-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ocuppation', models.JSONField(blank=True, default=list, null=True)),
                ('img', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=70)),
                ('bb_appearances', models.JSONField(blank=True, default=list, null=True)),
                ('bcs_appearances', models.JSONField(blank=True, default=list, null=True)),
                ('actor_portrayed', models.CharField(max_length=100)),
                ('category', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('season', models.CharField(max_length=5)),
                ('episode_number', models.IntegerField()),
                ('air_date', models.CharField(max_length=50)),
                ('characters', models.JSONField(blank=True, default=list, null=True)),
                ('series', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.IntegerField()),
                ('quote', models.CharField(max_length=400)),
                ('series', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episodios.character')),
            ],
        ),
    ]
